### ISSUE TITLE
webpack-cli

### ISSUE THREAD

**Issue by N-feng** [polyglot-microfrontends/root-config#7] opened 2021-07-06 10:35 UTC
TypeError: webpackMerge is not a function

**Comment by internettrans** [comment] 2021-07-07 04:20
I do not see this problem locally. Make sure you use `pnpm` rather than `npm` to ensure correct dependencies are installed.

Closing due to lack of detail and not able to reproduce the problem

**Closed as completed by internettrans** 2021-07-07 04:20 UTC
